### ISSUE TITLE
About the android.permission.BLUETOOTH

### ISSUE THREAD

**Issue by xvcvcvcxvddd** [EmmanuelPil/Android-java-code-utilities-widgets-for-Processing-for-Android#6]
Hi, thanks for sharing. I am trying to connect the Bluetooth. However, it always shows "java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10255 nor current process has android.permission.BLUETOOTH. I was wondering how can I give Bluetooth permission to the APP?
"

**Comment by jafal633** [comment]
Hi 

 To give Bluetooth permission to the APP


In the Processing’s IDE Android mode Menu/Android/Sketch permissions

On the APDE you can do that by choosing: Three dots / Sketch Properties / Sketch Permissions.

**Comment by xvcvcvcxvddd** [comment]
> 

Thank you so much. It was solved perfectly
